Repository phpmyadmin/phpmyadmin, pull requests merged in 2019-12, with the labels that each got.

#15603 Convert serverinfo bar to Bootstrap's breadcrumbs
  js/ajax.js
  js/functions.js
  js/navigation.js
  js/sql.js
  templates/menu/breadcrumbs.twig
  test/selenium/Database/OperationsTest.php
  test/selenium/LoginTest.php
  test/selenium/TestBase.php
  themes/bootstrap/scss/_breadcrumb.scss
  themes/bootstrap/scss/_common.scss
  themes/bootstrap/scss/_variables.scss
  themes/bootstrap/scss/theme.scss
  themes/metro/scss/_breadcrumbs.scss
  themes/metro/scss/_common.scss
  themes/metro/scss/_variables.scss
  themes/metro/scss/theme.scss
  themes/original/scss/_breadcrumbs.scss
  themes/original/scss/_common.scss
  themes/original/scss/_variables.scss
  themes/original/scss/theme.scss
  themes/pmahomme/scss/_breadcrumb.scss
  themes/pmahomme/scss/_common.scss
  themes/pmahomme/scss/_variables.scss
  themes/pmahomme/scss/theme.scss
Labels: enhancement, ui

#15610 Extracts HTML from UserPassword.php to twig template #14801
  libraries/classes/UserPassword.php
  templates/user_password.twig
Labels: enhancement, ui

#15624 Extract an interface from DatabaseInterface class
  libraries/classes/DatabaseInterface.php
  libraries/classes/Dbal/DbalInterface.php
  libraries/classes/Dbal/DbiExtension.php
  libraries/classes/Dbal/DbiMysqli.php
  test/classes/Dbal/DbiDummyTest.php
  test/classes/Dbal/DbiMysqliTest.php
  test/classes/Stubs/DbiDummy.php
Labels: enhancement

#15616 Extract HTML from php files
  libraries/classes/Display/ChangePassword.php
  templates/display/change_password/file_a.twig
  templates/display/change_password/file_b.twig
  templates/display/change_password/file_c.twig
  templates/display/change_password/file_d.twig
  templates/display/change_password/file_e.twig
Labels: enhancement

#15637 Prevent line wrap in DB structure size column
  templates/database/structure/structure_table_row.twig
Labels: ui
