Repository phpmyadmin/phpmyadmin, pull requests merged in 2020-09, with the labels that each got.

#16334 The PGP path finder is no longer maintained.
  doc/setup.rst
Labels: documentation

#16338 Refactor the ReplicationInfo class
  libraries/classes/Controllers/Database/StructureController.php
  libraries/classes/Controllers/Server/DatabasesController.php
  libraries/classes/Controllers/Server/ReplicationController.php
  libraries/classes/Controllers/Server/Status/StatusController.php
  libraries/classes/ReplicationGui.php
  libraries/classes/ReplicationInfo.php
  libraries/classes/Server/Status/Data.php
  test/classes/Controllers/Database/StructureControllerTest.php
  test/classes/Controllers/Server/Status/AdvisorControllerTest.php
  test/classes/Controllers/Server/Status/MonitorControllerTest.php
  test/classes/Controllers/Server/Status/ProcessesControllerTest.php
  test/classes/Controllers/Server/Status/QueriesControllerTest.php
  test/classes/Controllers/Server/Status/StatusControllerTest.php
  test/classes/Controllers/Server/Status/VariablesControllerTest.php
  test/classes/ReplicationGuiTest.php
  test/classes/Stubs/DbiDummy.php
Labels: refactoring

#16344 Remove list templates
  libraries/classes/Config/FormDisplayTemplate.php
  libraries/classes/Controllers/HomeController.php
  libraries/classes/Relation.php
  templates/config/form_display/tabs_top.twig
  templates/home/index.twig
  templates/list/item.twig
  templates/list/unordered.twig
  templates/relation/diagnostic_info.twig
Labels: refactoring

#16345 Remove Util::buildActionTitles and the titles global variable
  libraries/classes/Controllers/Database/RoutinesController.php
  libraries/classes/Controllers/Database/StructureController.php
  libraries/classes/Controllers/Database/TriggersController.php
  libraries/classes/Controllers/Table/ChangeController.php
  libraries/classes/Controllers/Table/SearchController.php
  libraries/classes/Controllers/Table/StructureController.php
  libraries/classes/Controllers/Table/TriggersController.php
  libraries/classes/Controllers/Table/ZoomSearchController.php
  libraries/classes/InsertEdit.php
  libraries/classes/Util.php
  templates/database/structure/favorite_anchor.twig
  templates/database/structure/structure_table_row.twig
  templates/table/search/input_box.twig
  templates/table/structure/display_structure.twig
  templates/table/zoom_search/result_form.twig
  test/classes/InsertEditTest.php
  test/classes/UtilTest.php
Labels: refactoring

#16348 Merge some columns definitions templates
  libraries/classes/Table/ColumnsDefinition.php
  templates/columns_definitions/column_adjust_privileges.twig
  templates/columns_definitions/column_attributes.twig
  templates/columns_definitions/column_auto_increment.twig
  templates/columns_definitions/column_comment.twig
  templates/columns_definitions/column_default.twig
  templates/columns_definitions/column_extra.twig
  templates/columns_definitions/column_indexes.twig
  templates/columns_definitions/column_length.twig
  templates/columns_definitions/column_null.twig
  templates/columns_definitions/column_type.twig
  templates/columns_definitions/column_virtuality.twig
  templates/columns_definitions/mime_type.twig
  templates/columns_definitions/move_column.twig
  templates/columns_definitions/transformation.twig
  templates/columns_definitions/transformation_option.twig
  templates/database/central_columns/edit_table_row.twig
  templates/database/central_columns/main.twig
Labels: refactoring

#16366 Fix column definition form not showing default value
  ChangeLog
  libraries/classes/CentralColumns.php
  libraries/tbl_columns_definition_form.inc.php
  templates/columns_definitions/column_attributes.twig
  templates/database/central_columns/main.twig
Labels: bug

#16367 Refactor the CentralColumns class
  js/src/database/central_columns.js
  libraries/classes/CentralColumns.php
  libraries/classes/Controllers/Database/CentralColumnsController.php
  libraries/routes.php
  templates/database/central_columns/edit.twig
  templates/database/central_columns/edit_table_header.twig
  templates/database/central_columns/main.twig
  templates/database/central_columns/populate_columns.twig
  test/classes/CentralColumnsTest.php
Labels: refactoring
