Repository phpmyadmin/phpmyadmin, pull requests merged in 2020-05, with the labels that each got.

#15416 Export view option added in Export
  libraries/classes/Controllers/ExportController.php
  libraries/classes/Plugins/Export/ExportSql.php
Labels: enhancement

#15872 added continue session message
  libraries/classes/Plugins/AuthenticationPlugin.php
Labels: ui

#16071 Update JS dependencies
  js/database/multi_table_query.js
  js/vendor/jqplot/plugins/jqplot.cursor.js
  js/vendor/jqplot/plugins/jqplot.highlighter.js
  js/vendor/jquery/jquery.ba-hashchange-2.0.js
  js/vendor/jquery/jquery.debounce-1.0.5.js
  js/vendor/jquery/jquery.debounce-1.0.6.js
  js/vendor/jquery/jquery.event.drag-2.2.js
  js/vendor/jquery/jquery.fullscreen.js
  js/vendor/jquery/jquery.md5.js
  js/vendor/jquery/jquery.sortableTable.js
  js/vendor/jquery/jquery.tablesorter.js
  js/vendor/jquery/jquery.uitablefilter.js
  js/vendor/sprintf.js
  libraries/classes/Header.php
  package.json
  scripts/sync-js-vendor-files.sh
  yarn.lock
Labels: enhancement

#16120 Improve TravisCI config
  .travis.yml
  test/config.e2e.inc.php
  test/nginx.conf
  test/start-local-server
Labels: enhancement

#16115 Change eg. to e.g. x2
  libraries/classes/Config/Descriptions.php
Labels: translation

#15779 Informing the user about the HEX conversion scheme of Integers
  js/messages.php
  js/table/change.js
Labels: enhancement, ui

#16122 Remove mysql extension checks as it was removed in php 7.0
  libraries/classes/Config/Validator.php
  libraries/classes/Database/Routines.php
  libraries/classes/DatabaseInterface.php
  libraries/classes/Util.php
  templates/display/results/table_navigation_button.twig
Labels: enhancement

#16123 Fix #16110 - Incorrect mouseover highlighting
  themes/bootstrap/scss/_common.scss
  themes/metro/scss/_common.scss
  themes/pmahomme/scss/_common.scss
Labels: ui

#16124 Fix #15101 - Margin before checkbox
  themes/pmahomme/scss/_common.scss
Labels: ui

#15951 fix #15950: updated datetime picker UI
  themes/bootstrap/scss/_common.scss
  themes/original/scss/_common.scss
  themes/pmahomme/scss/_common.scss
Labels: ui

#16128 Fix #16119 - ActionLinksMode icons issue
  templates/database/operations/index.twig
Labels: bug
