Repository phpmyadmin/phpmyadmin, pull requests merged in 2020-04, with the labels that each got.

#16066 Fixes #16050: Added proper classes to html elements …
  templates/login/form.twig
Labels: bug, enhancement, ui

#15915 fix Unexpected UI in Navigation Setting / Server
  libraries/classes/Config/FormDisplayTemplate.php
Labels: ui

#15943 Fix #15939: Form labels alignment issue.
  themes/bootstrap/scss/_common.scss
  themes/metro/scss/_common.scss
  themes/pmahomme/scss/_common.scss
Labels: ui

#15930 Fix #15929: Metro ui settings page navigation panel icon display.
  themes/metro/scss/_navigation.scss
Labels: ui

#15959 Fix #15957: rename export database model button.
  themes/bootstrap/scss/_common.scss
Labels: ui

#15625 Fix #15619 - Text alignment issue in structure table
  themes/bootstrap/scss/_common.scss
  themes/metro/scss/_common.scss
  themes/original/scss/_common.scss
  themes/pmahomme/scss/_common.scss
Labels: enhancement

#16100 Add Psalm
  .gitattributes
  composer.json
  libraries/classes/Advisor.php
  libraries/classes/Controllers/Table/StructureController.php
  libraries/classes/Core.php
  libraries/classes/Database/Designer/DesignerTable.php
  libraries/classes/Database/Routines.php
  libraries/classes/DatabaseInterface.php
  libraries/classes/Gis/GisPolygon.php
  libraries/classes/Language.php
  libraries/classes/LanguageManager.php
  libraries/classes/Plugins.php
  libraries/classes/Plugins/Auth/AuthenticationSignon.php
  libraries/classes/Plugins/AuthenticationPlugin.php
  libraries/classes/Sanitize.php
  libraries/classes/Server/Privileges.php
  libraries/classes/Table/ColumnsDefinition.php
  libraries/classes/Template.php
  libraries/classes/Types.php
  libraries/classes/Util.php
  phpstan-baseline.neon
  psalm-baseline.xml
  psalm.xml
  scripts/create-release.sh
  test/classes/Server/PrivilegesTest.php
Labels: enhancement
