Repository phpmyadmin/phpmyadmin, pull requests merged in 2020-06, with the labels that each got.

#16181 Use button formaction attribute for table structure bulk links
  js/table/structure.js
  templates/table/structure/display_structure.twig
Labels: ui

#16182 Add list of supported browsers
  .browserslistrc
  .eslintrc.json
  js/console.js
  js/functions.js
  package.json
  yarn.lock
Labels: documentation

#16190 default password 'cbb74bc' changed to 'change_password'
  doc/setup.rst
Labels: documentation

#16192 Support twig 3
  composer.json
  libraries/classes/Controllers/Server/ReplicationController.php
  libraries/classes/Controllers/Server/Status/StatusController.php
  libraries/classes/Display/Error.php
  libraries/classes/Display/Export.php
  libraries/classes/Plugins/TwoFactor/Key.php
  libraries/classes/Template.php
  libraries/classes/Twig/I18n/TokenParserTrans.php
  libraries/classes/UserPreferencesHeader.php
  scripts/generate-twig-cache
  templates/columns_definitions/column_virtuality.twig
  templates/columns_definitions/partitions.twig
  templates/database/designer/main.twig
  templates/database/multi_table_query/form.twig
  templates/display/export/options_rows.twig
  templates/display/import/javascript.twig
  test/classes/Display/ErrorTest.php
  test/classes/UserPreferencesHeaderTest.php
Labels: enhancement

#16208 Lock inactive closed issues with GitHub actions
  .github/workflows/lock.yml
Labels: infrastructure

#16231 Fixes #16172 : allow change year in datetime or date
  js/functions.js
Labels: enhancement
