Repository phpmyadmin/phpmyadmin, pull requests merged in 2020-12, with the labels that each got.

#16491 Convert tables CSS to the Bootstrap table style
  js/src/functions.js
  js/src/server/privileges.js
  js/src/server/status/sorter.js
  js/src/server/status/variables.js
  js/src/server/variables.js
  libraries/classes/Database/Routines.php
  libraries/classes/Database/Triggers.php
  libraries/classes/Engines/Innodb.php
  libraries/classes/StorageEngine.php
  templates/database/central_columns/main.twig
  templates/database/events/editor_form.twig
  templates/database/events/index.twig
  templates/database/privileges/index.twig
  templates/database/qbe/ins_del_and_or_cell.twig
  templates/database/qbe/selection_form.twig
  templates/database/routines/index.twig
  templates/database/structure/body_for_table_summary.twig
  templates/database/structure/structure_table_row.twig
  templates/database/structure/table_header.twig
  templates/database/tracking/tables.twig
  templates/database/triggers/list.twig
  templates/server/collations/index.twig
  templates/server/databases/index.twig
  templates/server/engines/index.twig
  templates/server/plugins/index.twig
  templates/server/privileges/change_password.twig
  templates/server/privileges/privileges_summary.twig
  templates/server/privileges/users_overview.twig
  templates/server/status/processes/list.twig
  templates/server/status/queries/index.twig
  templates/server/status/status/index.twig
  templates/server/status/variables/index.twig
  templates/server/user_groups/user_groups.twig
  templates/server/variables/index.twig
  templates/table/privileges/index.twig
  templates/table/relation/common_form.twig
  templates/table/search/index.twig
  templates/table/structure/display_partitions.twig
  templates/table/structure/display_structure.twig
  templates/table/structure/display_table_stats.twig
  templates/table/tracking/main.twig
  templates/table/tracking/report_table.twig
  templates/table/tracking/structure_snapshot_columns.twig
  templates/table/tracking/structure_snapshot_indexes.twig
  templates/table/zoom_search/index.twig
  test/classes/Controllers/Server/CollationsControllerTest.php
  test/classes/Controllers/Server/EnginesControllerTest.php
  test/classes/Controllers/Server/PluginsControllerTest.php
  test/classes/Controllers/Server/Status/ProcessesControllerTest.php
  test/classes/Controllers/Server/Status/StatusControllerTest.php
  test/classes/Controllers/Server/Status/VariablesControllerTest.php
  test/classes/Engines/InnodbTest.php
  themes/bootstrap/scss/_common.scss
  themes/metro/scss/_common.scss
  themes/metro/scss/_tables.scss
  themes/original/scss/_common.scss
  themes/original/scss/_tables.scss
  themes/pmahomme/scss/_common.scss
  themes/pmahomme/scss/_tables.scss
Labels: enhancement, ui

#16531 Fix remaining issues due to #15823 changes
  js/src/functions.js
Labels: bug, ui

#16497 Fix #16495 Drop tables checkbox
  templates/database/structure/drop_form.twig
  templates/database/structure/empty_form.twig
  templates/table/delete/confirm.twig
  themes/bootstrap/scss/_designer.scss
  themes/metro/scss/_designer.scss
  themes/pmahomme/scss/_designer.scss
Labels: ui

#16513 Replace style image with Linear-gradient
  setup/styles.css
  themes/bootstrap/img/designer/Header.png
  themes/bootstrap/img/designer/Header_Linked.png
  themes/bootstrap/img/designer/left_panel_butt.png
  themes/bootstrap/img/select_bg.png
  themes/bootstrap/scss/_designer.scss
  themes/bootstrap/scss/_navigation.scss
  themes/original/scss/_navigation.scss
  themes/pmahomme/img/designer/Header.png
  themes/pmahomme/img/designer/Header_Linked.png
  themes/pmahomme/img/designer/bord.png
  themes/pmahomme/img/designer/left_panel_butt.png
  themes/pmahomme/img/left_nav_bg.png
  themes/pmahomme/img/select_bg.png
  themes/pmahomme/scss/_designer.scss
  themes/pmahomme/scss/_navigation.scss
  themes/pmahomme/scss/_variables.scss
Labels: ui
