Repository phpmyadmin/phpmyadmin, pull requests merged in 2020-11, with the labels that each got.

#16386 Use of SameSite=Strict
  doc/config.rst
  libraries/classes/Config.php
  libraries/config.default.php
Labels: hacktoberfest-accepted

#16452 Increase password characters limit during login
  libraries/classes/Plugins/Auth/AuthenticationCookie.php
Labels: documentation, enhancement

#16406 Add config parameters to support third-party reCAPTCHA v2 compatible APIs
  doc/config.rst
  libraries/classes/Config/Descriptions.php
  libraries/classes/Header.php
  libraries/classes/Plugins/Auth/AuthenticationCookie.php
  libraries/config.default.php
  templates/login/form.twig
  test/classes/Plugins/Auth/AuthenticationCookieTest.php
Labels: enhancement

#16417 Fixed all 4 buttons for Wide-SCreens
  themes/bootstrap/scss/_common.scss
  themes/metro/scss/_common.scss
  themes/original/scss/_common.scss
  themes/pmahomme/scss/_common.scss
Labels: enhancement, ui

#16392 Moved tools section to left on large devices (Bootstrap xl)
  themes/bootstrap/scss/_common.scss
  themes/metro/scss/_common.scss
  themes/pmahomme/scss/_common.scss
Labels: ui

#16087 Glossary reworked
  doc/config.rst
  doc/faq.rst
  doc/glossary.rst
  doc/setup.rst
Labels: documentation

#16455 Add documentation link for installing on IBM Cloud.
  doc/setup.rst
Labels: documentation

#16466 Implement MysqlSslWarningSafeHosts to fix #15584
  doc/config.rst
  libraries/classes/Html/Generator.php
  libraries/config.default.php
  test/classes/Html/GeneratorTest.php
Labels: enhancement

#16472 #16418 - Make MariaDBMySQLKBS optional
  libraries/classes/Controllers/Server/VariablesController.php
  libraries/classes/Html/Generator.php
  libraries/classes/Providers/ServerVariables/MariaDbMySqlKbsProvider.php
  libraries/classes/Providers/ServerVariables/ServerVariablesProvider.php
  libraries/classes/Providers/ServerVariables/ServerVariablesProviderInterface.php
  libraries/classes/Providers/ServerVariables/VoidProvider.php
  test/classes/Controllers/Server/VariablesControllerTest.php
Labels: enhancement

#15912 Added Rename Button to use RENAME INDEX syntax of MySQL
  js/src/functions.js
  js/src/indexes.js
  libraries/classes/Controllers/JavaScriptMessagesController.php
  libraries/classes/Controllers/Table/IndexesController.php
  libraries/classes/Query/Compatibility.php
  libraries/classes/Query/Generator.php
  libraries/routes.php
  templates/table/index_rename_form.twig
  templates/table/structure/display_structure.twig
  test/classes/Controllers/Table/IndexesControllerTest.php
  themes/bootstrap/img/b_rename.svg
  themes/bootstrap/scss/_icons.scss
  themes/metro/img/b_rename.svg
  themes/metro/scss/_icons.scss
  themes/original/img/b_rename.svg
  themes/original/scss/_icons.scss
  themes/pmahomme/img/b_rename.svg
  themes/pmahomme/scss/_icons.scss
Labels: enhancement

#16478 Improve documentation about installing with Debian and Ubuntu
  doc/setup.rst
Labels: documentation
