Repository phpmyadmin/phpmyadmin, pull requests merged in 2020-02, with the labels that each got.

#15914 Fix #15910: Modify SCSS in all themes for all fieldsets of
  themes/bootstrap/scss/_common.scss
  themes/metro/scss/_common.scss
  themes/original/scss/_common.scss
  themes/pmahomme/scss/_common.scss
Labels: ui

#15953 Refactor the route definition file
  index.php
  js/database/multi_table_query.js
  js/export.js
  libraries/classes/Controllers/AjaxController.php
  libraries/classes/Controllers/BrowseForeignersController.php
  libraries/classes/Controllers/CheckRelationsController.php
  libraries/classes/Controllers/Database/DataDictionaryController.php
  libraries/classes/Controllers/Database/MultiTableQueryController.php
  libraries/classes/Controllers/Database/QueryByExampleController.php
  libraries/classes/Controllers/Database/RoutinesController.php
  libraries/classes/Controllers/Database/SqlAutoCompleteController.php
  libraries/classes/Controllers/Database/SqlFormatController.php
  libraries/classes/Controllers/Database/StructureController.php
  libraries/classes/Controllers/GisDataEditorController.php
  libraries/classes/Controllers/HomeController.php
  libraries/classes/Controllers/LintController.php
  libraries/classes/Controllers/Server/BinlogController.php
  libraries/classes/Controllers/Server/CollationsController.php
  libraries/classes/Controllers/Server/DatabasesController.php
  libraries/classes/Controllers/Server/EnginesController.php
  libraries/classes/Controllers/Server/PluginsController.php
  libraries/classes/Controllers/Server/ReplicationController.php
  libraries/classes/Controllers/Server/SqlController.php
  libraries/classes/Controllers/Server/Status/AdvisorController.php
  libraries/classes/Controllers/Server/Status/MonitorController.php
  libraries/classes/Controllers/Server/Status/ProcessesController.php
  libraries/classes/Controllers/Server/Status/QueriesController.php
  libraries/classes/Controllers/Server/Status/StatusController.php
  libraries/classes/Controllers/Server/Status/VariablesController.php
  libraries/classes/Controllers/Server/VariablesController.php
  libraries/classes/Controllers/ThemesController.php
  libraries/classes/Controllers/TransformationOverviewController.php
  libraries/classes/Database/MultiTableQuery.php
  libraries/classes/Menu.php
  libraries/routes.php
  phpstan-baseline.neon
  templates/database/multi_table_query/form.twig
  templates/database/structure/index.twig
  test/classes/Controllers/Database/StructureControllerTest.php
  test/classes/Controllers/Server/BinlogControllerTest.php
  test/classes/Controllers/Server/CollationsControllerTest.php
  test/classes/Controllers/Server/DatabasesControllerTest.php
  test/classes/Controllers/Server/EnginesControllerTest.php
  test/classes/Controllers/Server/PluginsControllerTest.php
  test/classes/Controllers/Server/Status/AdvisorControllerTest.php
  test/classes/Controllers/Server/Status/MonitorControllerTest.php
  test/classes/Controllers/Server/Status/ProcessesControllerTest.php
  test/classes/Controllers/Server/Status/QueriesControllerTest.php
  test/classes/Controllers/Server/Status/StatusControllerTest.php
  test/classes/Controllers/Server/Status/VariablesControllerTest.php
  test/classes/Controllers/Server/VariablesControllerTest.php
  test/classes/Controllers/TransformationOverviewControllerTest.php
  test/classes/Stubs/Response.php
Labels: refactoring

#15884 Fix #15880: Change Show Query Link to button
  js/sql.js
  templates/database/search/main.twig
Labels: enhancement, ui

#15967 Added missing CSS class to simulate query button
  js/functions.js
Labels: ui

#15979 Modal drag on routines fixes #15937
  js/rte.js
Labels: ui

#15969 Fix #15968: Add database table print button style
  js/functions.js
Labels: ui

#15585 Fix #15582 Don't disable "Empty"-button after clicking
  js/database/structure.js
Labels: enhancement

#15678 Stay on table structure page.
  js/table/structure.js
Labels: enhancement

#16000 Selenium fixes try 1
  test/selenium/CreateDropDatabaseTest.php
  test/selenium/Database/ProceduresTest.php
  test/selenium/Table/OperationsTest.php
  test/selenium/TestBase.php
Labels: help wanted
