Repository phpmyadmin/phpmyadmin, pull requests merged in 2020-08, with the labels that each got.

#16298 Fix some typos found with yaspeller
  doc/config.rst
  doc/faq.rst
  doc/import_export.rst
  doc/security.rst
  doc/themes.rst
  doc/transformations.rst
  libraries/classes/Language.php
Labels: documentation

#16273 Fix #14644 - Use Doctum instead of Sami
  .gitattributes
  .travis.yml
  phpcs.xml.dist
  phpstan.neon.dist
  test/doctum-config.php
  test/sami-config.php
Labels: infrastructure

#16322 Create dedicated pages for table maintenance actions
  js/database/structure.js
  libraries/classes/Controllers/Database/QueryByExampleController.php
  libraries/classes/Controllers/Database/StructureController.php
  libraries/classes/Controllers/ImportController.php
  libraries/classes/Controllers/SqlController.php
  libraries/classes/Controllers/Table/DeleteController.php
  libraries/classes/Controllers/Table/MaintenanceController.php
  libraries/classes/Controllers/Table/OperationsController.php
  libraries/classes/Controllers/Table/SearchController.php
  libraries/classes/Controllers/Table/StructureController.php
  libraries/classes/Database/MultiTableQuery.php
  libraries/classes/Operations.php
  libraries/classes/Sql.php
  libraries/classes/Table/Maintenance.php
  libraries/routes.php
  libraries/services.php
  libraries/services_controllers.php
  templates/database/structure/check_table.twig
  templates/sql/sql_query_results.twig
  templates/table/maintenance/analyze.twig
  templates/table/maintenance/check.twig
  templates/table/maintenance/checksum.twig
  templates/table/maintenance/optimize.twig
  templates/table/maintenance/repair.twig
  templates/table/operations/index.twig
  themes/bootstrap/scss/_bootstrap.scss
Labels: refactoring

#16323 Remove the advisory rules file parser
  libraries/advisory_rules_generic.php
  libraries/advisory_rules_generic.txt
  libraries/advisory_rules_mysql_before80003.php
  libraries/advisory_rules_mysql_before80003.txt
  libraries/classes/Advisor.php
  libraries/classes/Command/AdvisoryRulesCommand.php
  psalm-baseline.xml
  scripts/console
  scripts/update-po
  templates/server/status/advisor/index.twig
  test/classes/AdvisorTest.php
Labels: refactoring
