Repository phpmyadmin/phpmyadmin, pull requests merged in 2020-01, with the labels that each got.

#15730 Fixed icon by removing width
  themes/metro/scss/_enum-editor.scss
  themes/pmahomme/scss/_enum-editor.scss
Labels: ui

#15331 Add working environment configuration directive
  doc/config.rst
  libraries/classes/Template.php
  libraries/config.default.php
Labels: enhancement

#15744 Fix #15717
  js/functions.js
  libraries/classes/Controllers/Table/StructureController.php
Labels: ui

#15743 For revert.
  js/functions.js
  libraries/classes/Controllers/Table/StructureController.php
Labels: duplicate

#15784 Fixes virtuality dropdown menu
  libraries/classes/Normalization.php
  libraries/tbl_columns_definition_form.inc.php
  templates/columns_definitions/column_definitions_form.twig
  templates/columns_definitions/table_fields_definitions.twig
Labels: enhancement, ui

#15796 Usergroup twig work2
  libraries/classes/Server/UserGroups.php
  templates/server/user_groups/edit_user_groups.twig
  templates/server/user_groups/tab_list.twig
  templates/server/user_groups/user_groups.twig
  templates/server/user_groups/user_listings.twig
Labels: enhancement

#15420 Made required changes to add online transaction option
  libraries/classes/Controllers/Table/StructureController.php
  libraries/classes/CreateAddField.php
  templates/columns_definitions/column_definitions_form.twig
Labels: enhancement

#15775 Convert top menu to Bootstrap's navbar component
  js/menu_resizer.js
  templates/top_menu.twig
  themes/bootstrap/scss/_bootstrap.scss
  themes/bootstrap/scss/_common.scss
  themes/bootstrap/scss/_variables.scss
  themes/metro/scss/_common.scss
  themes/metro/scss/_navbar.scss
  themes/metro/scss/_variables.scss
  themes/metro/scss/theme.scss
  themes/original/scss/_common.scss
  themes/original/scss/_navbar.scss
  themes/original/scss/_variables.scss
  themes/original/scss/theme.scss
  themes/pmahomme/scss/_common.scss
  themes/pmahomme/scss/_navbar.scss
  themes/pmahomme/scss/_variables.scss
  themes/pmahomme/scss/theme.scss
Labels: ui

#15657 Fix #13864 - Prevent resetting of enum fields when adding new rows to current insertion batch
  js/table/change.js
Labels: ui

#15828 Fix for overlapping rows
  themes/original/scss/_common.scss
Labels: ui

#15842 Fixed Some Deprecated jquery selector
  js/table/change.js
Labels: enhancement

#15816 fixed font sizing
  themes/pmahomme/scss/_common.scss
Labels: ui

#15858 Added space between link
  libraries/classes/Html/Generator.php
Labels: ui

#15538 fixed html element typo in indexes.js
  js/error_report.js
  themes/original/scss/_common.scss
  themes/pmahomme/scss/_common.scss
Labels: enhancement

#15870 Fix #15194: Fix horizontal scroll of tables
  themes/bootstrap/scss/_common.scss
  themes/metro/scss/_common.scss
  themes/original/scss/_common.scss
  themes/pmahomme/scss/_common.scss
Labels: ui

#15871 Fix #14820: Table hide button in navigation
  themes/bootstrap/scss/_navigation.scss
  themes/metro/scss/_navigation.scss
  themes/original/scss/_navigation.scss
  themes/pmahomme/scss/_navigation.scss
Labels: enhancement, ui
