Repository phpmyadmin/phpmyadmin, pull requests merged in 2020-03, with the labels that each got.

#16007 Improve performance of dependency injection system by removing yaml parsing
  composer.json
  libraries/common.inc.php
  libraries/services.php
  libraries/services.yml
  libraries/services_controllers.php
  libraries/services_controllers.yml
  libraries/services_loader.php
  url.php
Labels: enhancement

#16011 autocomplete attributes added
  templates/login/form.twig
Labels: enhancement

#15881 Fix Preview SQL not visible on Index dialog Box
  js/indexes.js
  templates/table/index_form.twig
Labels: enhancement, ui

#15947 Fix #15944: Pagination table background issue
  themes/bootstrap/scss/_common.scss
  themes/metro/scss/_common.scss
  themes/pmahomme/scss/_common.scss
Labels: ui

#15894 Fix #15885 - Removed back labels from Metro login form
  themes/metro/scss/_common.scss
Labels: ui

#16031 Remove codacy/coverage dev-dependency
  .travis.yml
  composer.json
Labels: enhancement

#16040 require twig ^2.9
  composer.json
Labels: bug

#16028 Use caching to speed up route parsing
  index.php
  libraries/cache/.gitignore
  libraries/classes/Command/CacheWarmupCommand.php
  libraries/classes/Display/ImportAjax.php
  libraries/classes/Routing.php
  libraries/common.inc.php
  libraries/vendor_config.php
  phpcs.xml.dist
  phpstan.neon.dist
  phpunit.xml.dist
  scripts/console
  scripts/create-release.sh
  scripts/update-po
  test/classes/RoutingTest.php
Labels: enhancement
