Repository phpmyadmin/phpmyadmin, pull requests merged in 2021-04, with the labels that each got.

#16795 Fix #16605 - Fix vertical alignment issue
  themes/pmahomme/scss/_tables.scss
Labels: ui

#16781 Add padding to textarea (.edit_box)
  themes/pmahomme/scss/_common.scss
Labels: enhancement, ui

#16818 Remove useless htmlspecialchars on URL generation
  libraries/classes/Url.php
  templates/test/raw_output.twig
  test/classes/AdvisorTest.php
  test/classes/Controllers/Server/BinlogControllerTest.php
  test/classes/Html/GeneratorTest.php
  test/classes/Html/SecurityTest.php
  test/classes/InsertEditTest.php
  test/classes/Navigation/NavigationTest.php
  test/classes/Navigation/Nodes/NodeDatabaseChildTest.php
  test/classes/Plugins/Auth/AuthenticationConfigTest.php
  test/classes/Plugins/Transformations/TransformationPluginsTest.php
  test/classes/Server/PrivilegesTest.php
  test/classes/ThemeTest.php
  test/classes/UrlTest.php
  test/classes/UtilTest.php
Labels: hardening

#16831 Remove dump_buffer globals
  libraries/classes/Controllers/ExportController.php
  libraries/classes/Export.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: refactoring

#16814 Fix #15566 Designer - support RTL mode
  js/src/designer/move.js
  libraries/classes/Database/Designer.php
  templates/database/designer/database_tables.twig
  templates/database/designer/main.twig
Labels: ui

#16844 Redesign the Charsets and Collations page
  templates/server/collations/index.twig
  test/classes/Controllers/Server/CollationsControllerTest.php
  themes/metro/scss/_list-group.scss
  themes/metro/scss/_variables.scss
  themes/original/scss/_list-group.scss
  themes/original/scss/_variables.scss
  themes/pmahomme/scss/_list-group.scss
  themes/pmahomme/scss/_variables.scss
Labels: refactoring, ui

#16830 Fix #16829 - Add NOT LIKE %...% operator to Table search
  js/src/database/query_generator.js
  js/src/table/change.js
  libraries/classes/Table/Search.php
  libraries/classes/Types.php
  templates/database/multi_table_query/form.twig
  test/classes/TypesTest.php
Labels: enhancement

#16639 Fix #16637 - Show popup on search without tables
  js/src/database/search.js
  libraries/classes/Controllers/JavaScriptMessagesController.php
  templates/database/search/main.twig
Labels: enhancement, ui

#16857 Replace edit user group dialog with a modal
  .eslintrc.json
  js/src/server/privileges.js
  templates/server/privileges/choose_user_group.twig
  templates/server/privileges/new_user_ajax.twig
  templates/server/privileges/users_overview.twig
Labels: refactoring
