Repository phpmyadmin/phpmyadmin, pull requests merged in 2021-01, with the labels that each got.

#16524 Replace jQuery UI dialog with Bootstrap's modal
  js/src/database/structure.js
  js/src/error_report.js
  js/src/server/user_groups.js
  libraries/classes/Controllers/JavaScriptMessagesController.php
  libraries/classes/ErrorHandler.php
  libraries/classes/ErrorReport.php
  libraries/classes/Footer.php
  libraries/classes/Server/UserGroups.php
  phpstan-baseline.neon
  templates/database/structure/check_all_tables.twig
  templates/error/report_form.twig
  templates/footer.twig
  templates/server/user_groups/user_groups.twig
  test/classes/ErrorReportTest.php
  test/classes/Server/UserGroupsTest.php
  themes/bootstrap/scss/_common.scss
  themes/metro/scss/_common.scss
  themes/original/scss/_common.scss
  themes/pmahomme/scss/_common.scss
Labels: enhancement, ui

#16567 Redesign the Routines page
  js/src/database/routines.js
  templates/database/routines/editor_form.twig
  templates/database/routines/index.twig
  templates/database/routines/row.twig
Labels: enhancement, ui

#16571 Fixed typo in events editor
  templates/database/events/editor_form.twig
Labels: ui

#16573 Fixed spacing in routine, trigger and event editor form
  themes/metro/scss/_rte.scss
  themes/pmahomme/scss/_rte.scss
Labels: ui

#16547 Remove IcoMoon fonts from the metro theme
  doc/vendors.rst
  themes/bootstrap/img/b_rename.svg
  themes/bootstrap/scss/_common.scss
  themes/metro/fonts/IcoMoon.eot
  themes/metro/fonts/IcoMoon.svg
  themes/metro/fonts/IcoMoon.ttf
  themes/metro/fonts/IcoMoon.woff
  themes/metro/fonts/opensans-bold-webfont.eot
  themes/metro/fonts/opensans-bold-webfont.ttf
  themes/metro/fonts/opensans-bold-webfont.woff
  themes/metro/fonts/opensans-extrabold-webfont.eot
  themes/metro/fonts/opensans-extrabold-webfont.ttf
  themes/metro/fonts/opensans-extrabold-webfont.woff
  themes/metro/fonts/opensans-light-webfont.eot
  themes/metro/fonts/opensans-light-webfont.ttf
  themes/metro/fonts/opensans-light-webfont.woff
  themes/metro/fonts/opensans-regular-webfont.eot
  themes/metro/fonts/opensans-regular-webfont.ttf
  themes/metro/fonts/opensans-regular-webfont.woff
  themes/metro/img/b_rename.svg
  themes/metro/img/user.svg
  themes/metro/scss/_breadcrumbs.scss
  themes/metro/scss/_common.scss
  themes/metro/scss/_font.scss
  themes/metro/scss/_navigation.scss
  themes/original/img/b_rename.svg
  themes/original/scss/_common.scss
  themes/pmahomme/img/b_rename.svg
  themes/pmahomme/scss/_common.scss
Labels: ui

#16583 Migrate to GitHub actions most of our workflows
  .github/workflows/lint-and-analyse-php.yml
  .github/workflows/lint-docs.yml
  .github/workflows/other-tools.yml
  .github/workflows/tests.yml
  .travis.yml
  libraries/classes/Encoding.php
  test/ci-docs
  test/ci-phplint
  test/classes/EncodingTest.php
Labels: enhancement

#16579 Relation view with default to current database when creating relations
  ChangeLog
  templates/table/relation/foreign_key_row.twig
  templates/table/relation/relational_dropdown.twig
Labels: enhancement

#16370 Modified CSS value font-size to revert instead of 1em.
  themes/metro/scss/_reboot.scss
  themes/original/scss/_reboot.scss
  themes/pmahomme/scss/_reboot.scss
Labels: ui

#16590 Make the console setup async
  js/src/console.js
  js/src/functions.js
  js/src/navigation.js
Labels: ui

#16581 Fix "PHP message: PHP Fatal error: Uncaught TypeError: htmlspecialch…
  libraries/classes/Config/FormDisplayTemplate.php
Labels: bug

#16593 Major performance improvements on browsing rows
  libraries/classes/Config/Descriptions.php
  libraries/classes/Display/Results.php
Labels: enhancement

#16317 Hint for Newline added on quick edit
  libraries/classes/Controllers/JavaScriptMessagesController.php
Labels: ui
