Repository phpmyadmin/phpmyadmin, pull requests merged in 2021-03, with the labels that each got.

#16710 Fix type error when exporting triggers to ODF
  libraries/classes/Plugins/Export/ExportOdt.php
Labels: bug

#16688 Fix #16552 - White on gray text on check table status results
  themes/pmahomme/scss/_variables.scss
Labels: ui

#16687 Fix #16659 - Column Drop arrow is not responsive
  js/src/makegrid.js
  themes/bootstrap/scss/_common.scss
  themes/metro/scss/_common.scss
  themes/original/scss/_common.scss
  themes/pmahomme/scss/_common.scss
Labels: ui

#16690 Fix #16677 - Font size of SQL query
  themes/bootstrap/scss/_common.scss
  themes/metro/scss/_common.scss
  themes/original/scss/_common.scss
Labels: ui

#16718 Fix #16604 - Table width 100%
  templates/database/events/index.twig
  templates/database/privileges/index.twig
  templates/database/routines/index.twig
  templates/database/tracking/tables.twig
  templates/database/triggers/list.twig
  templates/display/results/table.twig
  templates/server/privileges/users_overview.twig
  templates/server/status/processes/list.twig
  templates/table/privileges/index.twig
  templates/table/relation/common_form.twig
  templates/table/search/index.twig
  templates/table/structure/display_structure.twig
  templates/table/tracking/main.twig
  templates/table/tracking/structure_snapshot_columns.twig
  test/classes/Controllers/Server/Status/ProcessesControllerTest.php
Labels: ui

#16731 Fix #16716 - Rename disappears after column drop
  templates/indexes.twig
Labels: ui

#16736 Inject the error report modal on each request to error reports
  js/src/error_report.js
  libraries/classes/Controllers/ErrorReportController.php
  libraries/classes/ErrorReport.php
  libraries/classes/Footer.php
  templates/error/report_form.twig
  templates/error/report_modal.twig
  templates/footer.twig
Labels: bug, ui

#16749 Fix #16656 - Error messages are not translated
  js/src/table/change.js
Labels: ui
