Repository phpmyadmin/phpmyadmin, pull requests merged in 2021-05, with the labels that each got.

#16897 Remove navigation link generation from the Nodes
  libraries/classes/Navigation/NavigationTree.php
  libraries/classes/Navigation/NodeFactory.php
  libraries/classes/Navigation/Nodes/Node.php
  libraries/classes/Navigation/Nodes/NodeColumn.php
  libraries/classes/Navigation/Nodes/NodeColumnContainer.php
  libraries/classes/Navigation/Nodes/NodeDatabase.php
  libraries/classes/Navigation/Nodes/NodeDatabaseContainer.php
  libraries/classes/Navigation/Nodes/NodeEvent.php
  libraries/classes/Navigation/Nodes/NodeEventContainer.php
  libraries/classes/Navigation/Nodes/NodeFunction.php
  libraries/classes/Navigation/Nodes/NodeFunctionContainer.php
  libraries/classes/Navigation/Nodes/NodeIndex.php
  libraries/classes/Navigation/Nodes/NodeIndexContainer.php
  libraries/classes/Navigation/Nodes/NodeProcedure.php
  libraries/classes/Navigation/Nodes/NodeProcedureContainer.php
  libraries/classes/Navigation/Nodes/NodeTable.php
  libraries/classes/Navigation/Nodes/NodeTableContainer.php
  libraries/classes/Navigation/Nodes/NodeTrigger.php
  libraries/classes/Navigation/Nodes/NodeTriggerContainer.php
  libraries/classes/Navigation/Nodes/NodeView.php
  libraries/classes/Navigation/Nodes/NodeViewContainer.php
  phpstan-baseline.neon
  psalm-baseline.xml
  test/classes/Navigation/Nodes/NodeColumnContainerTest.php
  test/classes/Navigation/Nodes/NodeColumnTest.php
  test/classes/Navigation/Nodes/NodeDatabaseTest.php
  test/classes/Navigation/Nodes/NodeEventContainerTest.php
  test/classes/Navigation/Nodes/NodeEventTest.php
  test/classes/Navigation/Nodes/NodeFunctionContainerTest.php
  test/classes/Navigation/Nodes/NodeFunctionTest.php
  test/classes/Navigation/Nodes/NodeIndexContainerTest.php
  test/classes/Navigation/Nodes/NodeIndexTest.php
  test/classes/Navigation/Nodes/NodeProcedureContainerTest.php
  test/classes/Navigation/Nodes/NodeProcedureTest.php
  test/classes/Navigation/Nodes/NodeTableContainerTest.php
  test/classes/Navigation/Nodes/NodeTableTest.php
  test/classes/Navigation/Nodes/NodeTriggerContainerTest.php
  test/classes/Navigation/Nodes/NodeTriggerTest.php
  test/classes/Navigation/Nodes/NodeViewContainerTest.php
  test/classes/Navigation/Nodes/NodeViewTest.php
Labels: refactoring

#16909 Add roave/security-advisories to composer.json
  composer.json
Labels: hardening

#16910 Add DatabaseName value object
  composer.json
  libraries/classes/Controllers/Table/PartitionController.php
  libraries/classes/Dbal/DatabaseName.php
  libraries/classes/Table/Partition.php
  test/classes/Dbal/DatabaseNameTest.php
Labels: refactoring

#16913 Skip testImportOsm and testDoImport on 32-bit/s390x arch
  test/classes/Plugins/Import/ImportShpTest.php
Labels: packaging

#16933 Replace pma-auto-slider with Bootstrap's collapse
  js/src/database/multi_table_query.js
  js/src/database/query_generator.js
  js/src/functions.js
  js/src/indexes.js
  js/src/sql.js
  js/src/table/operations.js
  js/src/table/select.js
  js/src/table/structure.js
  templates/database/multi_table_query/form.twig
  templates/display/results/table.twig
  templates/table/index_form.twig
  templates/table/relation/common_form.twig
  templates/table/structure/display_structure.twig
  test/selenium/Database/ProceduresTest.php
  themes/bootstrap/scss/_common.scss
  themes/metro/scss/_common.scss
  themes/original/scss/_common.scss
  themes/pmahomme/scss/_common.scss
Labels: refactoring

#16927 Replace designer group dialogs with modals
  js/src/designer/move.js
  templates/database/designer/main.twig
Labels: refactoring
