Repository phpmyadmin/phpmyadmin, pull requests merged in 2021-07, with the labels that each got.

#16986 Fix table width on Insert and Query by example pages
  templates/database/qbe/selection_form.twig
Labels: bug, ui

#16934 Fix #15691 - disable last checkbox
  js/src/makegrid.js
Labels: enhancement, ui

#16767 Fix #16138 - Ignore the length of the integer types and show a warning
  js/src/functions.js
  libraries/classes/Html/Generator.php
  libraries/classes/Query/Compatibility.php
  libraries/classes/Table.php
  libraries/classes/Table/ColumnsDefinition.php
  templates/columns_definitions/column_definitions_form.twig
Labels: enhancement, ui

#16983 Add suport to the Mroonga engine
  libraries/classes/Controllers/Database/StructureController.php
  libraries/classes/DatabaseInterface.php
  libraries/classes/StorageEngine.php
  test/classes/Controllers/Database/StructureControllerTest.php
  test/classes/StorageEngineTest.php
  test/classes/Stubs/DbiDummy.php
Labels: duplicate

#16928 Double click column name to directly copy to clipboard
  js/src/functions.js
  js/src/makegrid.js
  libraries/classes/Controllers/JavaScriptMessagesController.php
Labels: enhancement, ui

#16750 Fix #16425 - Add DELETE FROM table
  js/src/table/operations.js
  libraries/classes/Controllers/JavaScriptMessagesController.php
  templates/table/operations/index.twig
Labels: enhancement, ui

#17024 Fix table width on Query statistics and Server pages
  templates/server/status/queries/index.twig
  templates/server/status/status/index.twig
  test/classes/Controllers/Server/Status/StatusControllerTest.php
Labels: ui

#16925 Replace Export privileges group dialog with a modal
  js/src/server/privileges.js
  libraries/classes/Controllers/Server/PrivilegesController.php
  libraries/classes/Server/Privileges.php
  templates/export_modal.twig
Labels: ui

#16889 [UI] #16482 - Select All link for table-specific privileges
  js/src/server/privileges.js
  templates/server/privileges/privileges_table.twig
Labels: enhancement, ui

#17025 Create `Settings` value object for `$cfg` global
  libraries/classes/Config/Settings.php
  libraries/classes/Config/Settings/Export.php
  libraries/classes/Config/Settings/Import.php
  libraries/classes/Config/Settings/Schema.php
  libraries/classes/Config/Settings/Server.php
  libraries/classes/Config/Settings/Transformations.php
  psalm-baseline.xml
  test/classes/Config/Settings/ExportTest.php
  test/classes/Config/SettingsTest.php
Labels: refactoring
