Repository phpmyadmin/phpmyadmin, pull requests merged in 2022-10, with the labels that each got.

#17752 Remove Sodium polyfill
  .github/workflows/tests.yml
  composer.json
  scripts/create-release.sh
Labels: hardening

#17758 Fix issue - Edit/Copy/Delete row doesn't work when using GROUP BY
  libraries/classes/FieldMetadata.php
  libraries/classes/Util.php
  test/classes/FieldMetadataTest.php
  test/classes/UtilTest.php
Labels: hacktoberfest-accepted

#17753 Adding inputmode numeric to integer fields
  libraries/classes/InsertEdit.php
  test/classes/Controllers/Table/ChangeControllerTest.php
  test/classes/InsertEditTest.php
Labels: hacktoberfest-accepted

#17764 Add basic routing system for setup pages
  js/src/setup/scripts.js
  libraries/classes/Controllers/Setup/MainController.php
  libraries/classes/Controllers/Setup/ShowConfigController.php
  libraries/classes/Setup/FormProcessing.php
  setup/config.php
  setup/index.php
  setup/validate.php
  templates/setup/base.twig
  templates/setup/config/index.twig
  templates/setup/error.twig
  templates/setup/home/index.twig
  test/classes/Setup/FormProcessingTest.php
Labels: hacktoberfest-accepted

#17788 Ref #12262 - Remove inline styles
  templates/database/structure/check_all_tables.twig
Labels: ui

#17809 Adds support for SHA2 function
  js/src/modules/doc-links.js
  js/src/table/change.js
  libraries/classes/InsertEdit.php
  libraries/classes/Types.php
  test/classes/TypesTest.php
Labels: enhancement

#17787 Replace POST-var access with Serverrequest object - pt 2
  libraries/classes/Controllers/Table/Structure/AddIndexController.php
  libraries/classes/Controllers/Table/Structure/CentralColumnsAddController.php
  libraries/classes/Controllers/Table/Structure/CentralColumnsRemoveController.php
  libraries/classes/Controllers/Table/Structure/ChangeController.php
  libraries/classes/Controllers/Table/Structure/FulltextController.php
  libraries/classes/Controllers/Table/Structure/MoveColumnsController.php
  libraries/classes/Controllers/Table/Structure/PrimaryController.php
  libraries/classes/Controllers/Table/Structure/ReservedWordCheckController.php
  libraries/classes/Controllers/Table/Structure/SpatialController.php
  libraries/classes/Controllers/Table/Structure/UniqueController.php
  test/classes/Controllers/Table/Structure/SpatialControllerTest.php
  test/classes/Controllers/Table/Structure/UniqueControllerTest.php
Labels: hacktoberfest-accepted

#17746 Use Database type instead of string
  libraries/classes/Controllers/Export/ExportController.php
  libraries/classes/Controllers/Table/AddFieldController.php
  libraries/classes/CreateAddField.php
  libraries/classes/Export.php
  test/classes/ExportTest.php
Labels: hacktoberfest-accepted

#17798 Fixed Typos in README.rst
  README.rst
Labels: hacktoberfest-accepted

#17839 Fix #17812 - Add missing styles to buttons on "Page-related settings" modal
  js/src/page_settings.js
Labels: ui

#17801 Fix #13773 - Export page of Settings is not responsive
  templates/preferences/header.twig
Labels: ui

#17817 Use ServerRequest Object to access POST-vars
  libraries/classes/Controllers/View/CreateController.php
Labels: hacktoberfest-accepted

#17818 Use ServerRequest Object instead superglobals - CollationController
  libraries/classes/Controllers/Database/Operations/CollationController.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: hacktoberfest-accepted

#17819 #17769 Use ServerRequest Object to access POST-vars
  libraries/classes/Controllers/Server/ReplicationController.php
  libraries/classes/Controllers/Table/TrackingController.php
Labels: hacktoberfest-accepted

#17840 Fix links to databases for information_schema.SCHEMATA
  libraries/classes/Config/SpecialSchemaLinks.php
Labels: hacktoberfest-accepted

#17820 Ref #16276 - Reduce the usage of SuperGlobals in Tracking and UserPassword
  libraries/classes/Controllers/Table/TrackingController.php
  libraries/classes/Controllers/UserPasswordController.php
  libraries/classes/Tracking.php
  libraries/classes/UserPassword.php
  test/classes/TrackingTest.php
  test/classes/UserPasswordTest.php
Labels: hacktoberfest-accepted

#17824 get data from request object instead of POST global
  libraries/classes/Controllers/View/OperationsController.php
Labels: hacktoberfest-accepted

#17828 Ref #17769 - Replaced superglobal in LintController
  libraries/classes/Controllers/Database/SearchController.php
  libraries/classes/Controllers/Database/SqlController.php
  libraries/classes/Controllers/LintController.php
  libraries/classes/Controllers/SchemaExportController.php
  libraries/classes/Controllers/UserPasswordController.php
Labels: hacktoberfest-accepted

#17665 Fix #17553 - [Metro] Unreadable links and UI fixes/improvements
  themes/metro/img/b_deltbl_white.png
  themes/metro/scss/_alert.scss
  themes/metro/scss/_common.scss
  themes/metro/scss/_icons.scss
  themes/metro/scss/_navigation.scss
Labels: enhancement, ui

#17829 Abstract & CheckRelations Controllers - Refactored
  libraries/classes/Controllers/AbstractController.php
  libraries/classes/Controllers/CheckRelationsController.php
Labels: hacktoberfest-accepted

#17844 Fix #16042 - gzip encoding in Firefox for 5.2.x
  libraries/classes/Core.php
  test/classes/CoreTest.php
Labels: hacktoberfest-accepted
