Repository phpmyadmin/phpmyadmin, pull requests merged in 2022-04, with the labels that each got.

#17438 Allow removing DEFINER clause from exported SQL
  doc/config.rst
  libraries/classes/Config/Descriptions.php
  libraries/classes/Config/Settings/Export.php
  libraries/classes/Plugins/Export/ExportSql.php
  libraries/config.default.php
Labels: enhancement

#17280 fix themes cards heights
  templates/home/themes.twig
  themes/bootstrap/scss/_card.scss
  themes/bootstrap/scss/_variables.scss
  themes/bootstrap/scss/theme.scss
  themes/metro/scss/_card.scss
  themes/metro/scss/_variables.scss
  themes/original/scss/_card.scss
  themes/original/scss/_variables.scss
  themes/pmahomme/scss/_card.scss
  themes/pmahomme/scss/_variables.scss
Labels: ui

#17278 improve null div ux
  themes/bootstrap/scss/_common.scss
  themes/metro/scss/_common.scss
  themes/original/scss/_common.scss
  themes/pmahomme/scss/_common.scss
Labels: enhancement, ui

#17337 Fix #17335: The menu to toggle column visibility is half hidden
  themes/bootstrap/scss/_common.scss
  themes/metro/scss/_common.scss
  themes/original/scss/_common.scss
  themes/pmahomme/scss/_common.scss
Labels: ui
