Repository phpmyadmin/phpmyadmin, pull requests merged in 2023-07, with the labels that each got.

#18454 Fix datefield calendar display when changing NULL state
  js/src/makegrid.js
Labels: ui

#18524 Extract dependency on Relation from the Node classes
  libraries/classes/Navigation/Navigation.php
  libraries/classes/Navigation/NavigationTree.php
  libraries/classes/Navigation/Nodes/Node.php
  libraries/classes/Navigation/Nodes/NodeDatabase.php
  libraries/classes/Navigation/Nodes/NodeDatabaseChild.php
  libraries/classes/Navigation/Nodes/NodeTable.php
  test/classes/Navigation/NavigationTreeTest.php
  test/classes/Navigation/NodeFactoryTest.php
  test/classes/Navigation/Nodes/NodeColumnContainerTest.php
  test/classes/Navigation/Nodes/NodeColumnTest.php
  test/classes/Navigation/Nodes/NodeDatabaseChildTest.php
  test/classes/Navigation/Nodes/NodeDatabaseTest.php
  test/classes/Navigation/Nodes/NodeEventContainerTest.php
  test/classes/Navigation/Nodes/NodeEventTest.php
  test/classes/Navigation/Nodes/NodeFunctionContainerTest.php
  test/classes/Navigation/Nodes/NodeFunctionTest.php
  test/classes/Navigation/Nodes/NodeIndexContainerTest.php
  test/classes/Navigation/Nodes/NodeIndexTest.php
  test/classes/Navigation/Nodes/NodeProcedureContainerTest.php
  test/classes/Navigation/Nodes/NodeProcedureTest.php
  test/classes/Navigation/Nodes/NodeTableContainerTest.php
  test/classes/Navigation/Nodes/NodeTableTest.php
  test/classes/Navigation/Nodes/NodeTest.php
  test/classes/Navigation/Nodes/NodeTriggerContainerTest.php
  test/classes/Navigation/Nodes/NodeTriggerTest.php
  test/classes/Navigation/Nodes/NodeViewContainerTest.php
  test/classes/Navigation/Nodes/NodeViewTest.php
Labels: refactoring

#18568 Extract response handling from Routines, Triggers and Events classes
  libraries/classes/Controllers/Database/EventsController.php
  libraries/classes/Controllers/Database/RoutinesController.php
  libraries/classes/Controllers/Triggers/IndexController.php
  libraries/classes/Database/Events.php
  libraries/classes/Database/Routines.php
  libraries/classes/Triggers/Triggers.php
  libraries/services.php
  phpstan-baseline.neon
  psalm-baseline.xml
  test/classes/Controllers/Database/EventsControllerTest.php
  test/classes/Controllers/Database/RoutinesControllerTest.php
  test/classes/Controllers/Triggers/IndexControllerTest.php
  test/classes/Database/EventsTest.php
  test/classes/Database/RoutinesTest.php
  test/classes/Triggers/TriggersTest.php
Labels: refactoring

#18587 Remove the public/show_config_errors.php file
  libraries/classes/Config.php
  libraries/classes/Sanitize.php
  phpstan-baseline.neon
  psalm.xml
  public/show_config_errors.php
  scripts/check-release-excludes.sh
Labels: refactoring, hardening
