Repository phpmyadmin/phpmyadmin, pull requests merged in 2023-05, with the labels that each got.

#18360 Remove space and align right
  templates/database/structure/overhead.twig
  themes/pmahomme/scss/_tables.scss
Labels: bug, ui

#18363 Fix colspan number for actions column on database table list
  templates/database/structure/structure_table_row.twig
Labels: bug, ui

#18223 Add a configuration option to allow shared bookmarks: `$cfg['AllowSharedBookmarks']`
  doc/config.rst
  libraries/classes/Bookmark.php
  libraries/classes/Config/Descriptions.php
  libraries/classes/Config/Forms/Setup/SqlForm.php
  libraries/classes/Config/Settings.php
  libraries/classes/Sql.php
  libraries/classes/SqlQueryForm.php
  psalm-baseline.xml
  psalm.xml
  templates/sql/bookmark.twig
  templates/sql/query.twig
  test/classes/BookmarkTest.php
  test/classes/Config/SettingsTest.php
Labels: enhancement

#18452 Prefill the field field_default_value
  templates/database/central_columns/edit_table_row.twig
Labels: bug
