Repository phpmyadmin/phpmyadmin, pull requests merged in 2023-09, with the labels that each got.

#18685 Add a documentation note to the nopassword config
  doc/config.rst
Labels: documentation

#18683 Refactor Dbi::getColumn and getColumns
  phpstan-baseline.neon
  psalm-baseline.xml
  src/Column.php
  src/ConfigStorage/Relation.php
  src/Controllers/Database/CentralColumnsController.php
  src/Controllers/Database/DataDictionaryController.php
  src/Controllers/Database/SqlAutoCompleteController.php
  src/Controllers/Table/FindReplaceController.php
  src/Controllers/Table/RelationController.php
  src/Controllers/Table/SearchController.php
  src/Controllers/Table/Structure/ChangeController.php
  src/Controllers/Table/StructureController.php
  src/Controllers/Table/ZoomSearchController.php
  src/Database/CentralColumns.php
  src/Database/MultiTableQuery.php
  src/Database/Search.php
  src/DatabaseInterface.php
  src/Dbal/DbalInterface.php
  src/InsertEdit.php
  src/Normalization.php
  src/Plugins/Export/ExportHtmlword.php
  src/Plugins/Export/ExportLatex.php
  src/Plugins/Export/ExportMediawiki.php
  src/Plugins/Export/ExportOdt.php
  src/Plugins/Export/ExportSql.php
  src/Plugins/Export/ExportTexytext.php
  src/Plugins/Export/Helpers/Pdf.php
  src/Plugins/Import/ImportCsv.php
  src/Plugins/Schema/Pdf/PdfRelationSchema.php
  src/RecentFavoriteTable.php
  src/Replication/ReplicationGui.php
  src/Sql.php
  src/SqlQueryForm.php
  src/Table/ColumnsDefinition.php
  src/Tracking/Tracker.php
  src/Util.php
  templates/sql/query.twig
  templates/table/operations/index.twig
  templates/table/structure/display_structure.twig
  test/classes/ConfigStorage/RelationTest.php
  test/classes/Controllers/Table/FindReplaceControllerTest.php
  test/classes/Controllers/Table/SearchControllerTest.php
  test/classes/Controllers/Table/StructureControllerTest.php
  test/classes/Database/CentralColumnsTest.php
  test/classes/Database/SearchTest.php
  test/classes/InsertEditTest.php
  test/classes/NormalizationTest.php
  test/classes/Plugins/Export/ExportHtmlwordTest.php
  test/classes/Plugins/Export/ExportLatexTest.php
  test/classes/Plugins/Export/ExportMediawikiTest.php
  test/classes/Plugins/Export/ExportOdtTest.php
  test/classes/Plugins/Export/ExportSqlTest.php
  test/classes/Plugins/Export/ExportTexytextTest.php
  test/classes/SqlQueryFormTest.php
  test/classes/Stubs/DbiDummy.php
  test/classes/Table/ColumnsDefinitionTest.php
  test/classes/Tracking/TrackerTest.php
Labels: refactoring

#18690 Add security link to composer.json file
  composer.json
Labels: documentation

#18712 Fix GIS editor form layout
  js/src/gis_data_editor.js
  templates/gis_data_editor_form.twig
Labels: bug

#18738 Refactor the Core::getenv() method
  phpstan-baseline.neon
  psalm-baseline.xml
  src/Config.php
  src/Controllers/Preferences/ManageController.php
  src/Core.php
  src/Footer.php
  src/IpAllowDeny.php
  src/LanguageManager.php
  src/Plugins/Auth/AuthenticationHttp.php
  src/Plugins/TwoFactorPlugin.php
  src/Routing/Routing.php
  src/Util.php
  test/classes/CoreTest.php
Labels: refactoring
