Repository phpmyadmin/phpmyadmin, pull requests merged in 2023-08, with the labels that each got.

#18478 Remove empty option from enum select
  templates/sql/enum_column_dropdown.twig
Labels: ui

#18589 Add support for PSR-15 middleware
  composer.json
  libraries/classes/Application.php
  libraries/classes/ErrorHandler.php
  libraries/classes/Http/Handler/ApplicationHandler.php
  libraries/classes/Http/Handler/QueueRequestHandler.php
  libraries/classes/Middleware/ErrorHandling.php
  libraries/classes/Middleware/OutputBuffering.php
  libraries/classes/Middleware/PhpExtensionsChecking.php
  libraries/classes/OutputBuffering.php
  libraries/classes/ResponseRenderer.php
  phpstan-baseline.neon
  test/classes/Http/Handler/ApplicationHandlerTest.php
  test/classes/Http/Handler/QueueRequestHandlerTest.php
Labels: refactoring

#18649 Add color mode toggle at the top nav bar
  js/src/main.ts
  js/src/modules/themes-manager.ts
  libraries/classes/Controllers/ThemeSetController.php
  libraries/classes/Header.php
  templates/header.twig
Labels: refactoring

#18365 Change 'reCaptcha' text to 'Captcha'
  libraries/classes/Plugins/Auth/AuthenticationCookie.php
Labels: translation

#18668 Add number formatting to Total on Browse
  libraries/classes/Display/Results.php
  phpstan-baseline.neon
Labels: enhancement
