Repository phpmyadmin/phpmyadmin, pull requests merged in 2025-03, with the labels that each got.

#19568 Fix columns order in Table Structure
  src/Query/Generator.php
  tests/unit/ConfigStorage/RelationTest.php
  tests/unit/Controllers/BrowseForeignersControllerTest.php
  tests/unit/Controllers/Import/ImportControllerTest.php
  tests/unit/Controllers/Sql/EnumValuesControllerTest.php
  tests/unit/Controllers/Sql/SetValuesControllerTest.php
  tests/unit/Controllers/Table/CreateControllerTest.php
  tests/unit/Controllers/Table/GetFieldControllerTest.php
  tests/unit/DatabaseInterfaceTest.php
  tests/unit/Query/GeneratorTest.php
  tests/unit/SqlTest.php
  tests/unit/Stubs/DbiDummy.php
  tests/unit/Table/ColumnsDefinitionTest.php
Labels: Awaiting Author Updates

#19496 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#19540 Implement getValuesForCsvTable for CSV table type
  libraries/classes/Controllers/Database/StructureController.php
Labels: Enhancement
