Repository phpmyadmin/phpmyadmin, pull requests merged in 2025-01, with the labels that each got.

#19507 Replace $GLOBALS['l'] with TCPDF::setLanguageArray()
  libraries/classes/Language.php
  libraries/classes/Pdf.php
  phpstan-baseline.neon
  test/classes/AbstractTestCase.php
  test/classes/Html/SecurityTest.php
Labels: Bug

#19505 Remove underline for links on Bootstrap theme
  themes/bootstrap/scss/_variables.scss
Labels: ui

#19512 Fix sql editor height on multi-table query
  js/src/database/multi_table_query.js
Labels: ui

#19408 Fix #19242 - Removing the popup with auto-saved query message
  resources/js/src/sql.ts
  src/Controllers/JavaScriptMessagesController.php
Labels: ui

#19352 [Query Generator] support for `BETWEEN` and `NOT BETWEEN`
  resources/js/src/database/multi_table_query.ts
  resources/js/src/database/query_generator.ts
  src/Controllers/JavaScriptMessagesController.php
Labels: enhancement

#19514 Fix badge text color
  templates/server/collations/index.twig
  templates/table/maintenance/analyze.twig
  templates/table/maintenance/check.twig
  templates/table/maintenance/optimize.twig
  templates/table/maintenance/repair.twig
  templates/table/partition/analyze.twig
  templates/table/partition/check.twig
  templates/table/partition/optimize.twig
  templates/table/partition/repair.twig
  test/classes/Controllers/Server/CollationsControllerTest.php
  themes/pmahomme/scss/_common.scss
Labels: ui

#19465 documentation(setup.rst): Add all new ENV for the Docker image (mTLS) and added all missing ones
  doc/setup.rst
Labels: documentation

#19525 Add support for INSERT IGNORE into for non table imports
  src/Import/Import.php
  src/Plugins/Import/ImportCsv.php
  tests/unit/Plugins/Import/ImportCsvTest.php
Labels: enhancement
