Repository phpmyadmin/phpmyadmin, pull requests merged in 2025-08, with the labels that each got.

#19832 Fix export template update error
  phpstan-baseline.neon
  psalm-baseline.xml
  src/Controllers/Export/Template/UpdateController.php
  src/Export/Template.php
  tests/unit/Controllers/Export/Template/UpdateControllerTest.php
  tests/unit/Export/TemplateTest.php
Labels: Bug, affects/6.0

#19835 Fix error with import status message
  psalm-baseline.xml
  src/Controllers/Import/StatusController.php
  tests/unit/Controllers/Import/StatusControllerTest.php
Labels: Bug, affects/6.0, confirmed/6.0

#19834 Fix cell edit colors on Bootstrap theme
  public/themes/bootstrap/scss/_common.scss
Labels: UI
